version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 856380561074.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t blacklist-cloudops:latest .
      - docker tag blacklist-cloudops:latest 856380561074.dkr.ecr.us-east-1.amazonaws.com/blacklist-cloudops:latest
      - echo "Running tests..."
      - python ./run_tests.py 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 856380561074.dkr.ecr.us-east-1.amazonaws.com/blacklist-cloudops:latest
      - echo Writing Image Definitions file...
      - printf '[{"name":"blacklist-cloudops","imageUri":"856380561074.dkr.ecr.us-east-1.amazonaws.com/blacklist-cloudops:latest"}]' > imagedefinitions.json
      - printf '{"ImageURI":"856380561074.dkr.ecr.us-east-1.amazonaws.com/blacklist-cloudops:latest"}' > imageDetail.json
      - cat imagedefinitions.json 
artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
    - imageDetail.json
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json