services:
  blacklist:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - blacklist_db
    env_file:
      - .env
    environment:
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_APP_NAME: "BlacklistApp"
      NEW_RELIC_LOG: stdout
      NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: "true"

  blacklist_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pwd
      POSTGRES_DB: blacklist_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_blacklist_db:/var/lib/postgresql/data

volumes:
  postgres_data_blacklist_db: